In [1]:
import torch
import numpy as np
import pandas as pd

In [ ]:
# 텐서 생성
# 0-way Tensor : 0차원
scalar = torch.tensor(5)
print(scalar)
print(scalar.shape) # shape 가능. tensor 안에 ndarray 들어있음.


tensor(5)
torch.Size([])


In [ ]:
# 1차원
vector = torch.tensor([1, 2, 3, 4])     # 1차원 여러 개 값
print(vector)
print(vector.shape)     # ndarray에서는 (4,). 1차원. 4행(1차원은 행만 있음.)

tensor([1, 2, 3, 4])
torch.Size([4])


In [4]:
# 2차원
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [ ]:
# 3차원
tensor3d = torch.rand(2, 3, 4)      # random    # (행,열,폭)    # 24개 값이 임의로 들어감.
print(tensor3d)
print(tensor3d.shape)

In [6]:
# 2. 텐서 다루기
# 2.1 텐서의 데이터 타입 지정
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(int_tensor)
print(float_tensor)

tensor([1, 2, 3])
tensor([1., 2., 3.])


In [7]:
# 2.2 텐서 속성 확인
print(float_tensor)
print(f'Shape: {float_tensor.shape}')
print(f'Datatype: {float_tensor.dtype}')
print(f'Device: {float_tensor.device}')


tensor([1., 2., 3.])
Shape: torch.Size([3])
Datatype: torch.float32
Device: cpu


In [8]:
# 2.3 텐서 연산하기
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
print('덧셈:', a + b)
print('곱셈:', a * b)
print('제곱:', a ** 2)

덧셈: tensor([5., 7., 9.])
곱셈: tensor([ 4., 10., 18.])
제곱: tensor([1., 4., 9.])


In [9]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print('전체 합계:', x.sum())
print('열별 합계:', x.sum(dim=0))
print('행별 합계:', x.sum(dim=1))

전체 합계: tensor(21.)
열별 합계: tensor([5., 7., 9.])
행별 합계: tensor([ 6., 15.])


In [10]:
# 2.5 텐서 차원 변경
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
print('원래 텐서:', x)
reshaped = x.view(2, 3)
print('변형된 텐서:', reshaped)

원래 텐서: tensor([[1, 2],
        [3, 4],
        [5, 6]])
변형된 텐서: tensor([[1, 2, 3],
        [4, 5, 6]])


In [11]:
# 2.6 텐서 연결과 분리
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6]])


# 텐서 연결하기
concatenated = torch.cat([a, b], dim=0)
print('연결된 텐서:\n', concatenated)

연결된 텐서:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# 2.7 텐서 내적과 행렬곱
# 내적
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
dot = torch.dot(a, b)
print('Dot product:', dot)

Dot product: tensor(32)


In [13]:
# 행렬곱
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])


result = torch.matmul(A, B)
print(result)


tensor([[19, 22],
        [43, 50]])


In [16]:
# 광고비에 따른 매출액 예측
# DataLoader
path = 'https://bit.ly/advertising_csv' # 데이터
adv = pd.read_csv(path)                 # 데이터 프레임
adv.head()

,TV,Radio,Newspaper,Sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [17]:
adv.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [ ]:
target = 'Sales'                 # 원래답 
x = adv.drop(target, axis=1)    # 원래답 제거 => 데이터만 남음      # DataFrame
y = adv.loc[:, target]          # 원래답 추출                      # Series
x_np = x.values                 # 2차원 ndarray
y_np = y.values                 # 1차원 ndarray
print(type(x_np))               # ndarray
print(x_np.shape)               # (200, 3) 2차원.
print(type(y_np))               # ndarray
print(y_np.shape)               # (200,) 1차원

<class 'numpy.ndarray'>
(200, 3)
<class 'numpy.ndarray'>
(200,)


In [ ]:
# 넘파이 배열 x, y를 텐서로 변환
x_tensor = torch.tensor(x_np, dtype=torch.float32)      # 데이터
y_tensor = torch.tensor(y_np, dtype=torch.float32)      # 답
print(x_tensor.shape, y_tensor.shape)

torch.Size([200, 3]) torch.Size([200])


In [ ]:
from torch.utils.data import DataLoader, TensorDataset
dataset = TensorDataset(x_tensor, y_tensor)
print(dataset[:3])      # 튜플로 반환. (data, label)
print(len(dataset))


(tensor([[230.1000,  37.8000,  69.2000],
        [ 44.5000,  39.3000,  45.1000],
        [ 17.2000,  45.9000,  69.3000]]), tensor([22.1000, 10.4000,  9.3000]))
200


In [ ]:
# 데이터 로더 생성
# dataset = TensorDataset(x_tensor, y_tensor)

data_loader = DataLoader(dataset, batch_size = 32, shuffle = True)

In [ ]:
for n, batch in enumerate(data_loader):
    x_batch, y_batch = batch
    print(f'배치 {n}, x 배치 크기:{x_batch.shape}')

# '배치 0, x 배치 크기:torch.Size([32, 3])' 이 한 번에 들어가서 학습

배치 0, x 배치 크기:torch.Size([32, 3])
배치 1, x 배치 크기:torch.Size([32, 3])
배치 2, x 배치 크기:torch.Size([32, 3])
배치 3, x 배치 크기:torch.Size([32, 3])
배치 4, x 배치 크기:torch.Size([32, 3])
배치 5, x 배치 크기:torch.Size([32, 3])
배치 6, x 배치 크기:torch.Size([8, 3])


In [25]:
# 디바이스 할당
# 1. 데이터 준비
# 라이브러리 로딩
import torch
from torch import nn
import numpy as np
import pandas as pd


# 데이터 로딩 및 x, y 분할
path = 'https://bit.ly/advertising_csv'
adv = pd.read_csv(path)


target = 'Sales'
x = adv.drop(target, axis=1)
y = adv.loc[:, target]


# numpy로 변환한 다음 텐서로 변환
x_np = x.values
y_np = y.values
x_tensor = torch.tensor(x_np, dtype=torch.float32)
y_tensor = torch.tensor(y_np, dtype=torch.float32)


In [ ]:
# 디바이스 준비
# 무조건 쿠다 되는지 안되는지 확인하고 시작해야 함.

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using {device} device.')

Using cuda device.


In [ ]:
# 3. 모델과 데이터셋을 디바이스 할당
# 모델을 디바이스(GPU)에 할당하기
model = nn.Sequential( nn.Linear(3, 1) )
model = model.to(device)    # 현재 디바이스는 cuda  # 모델 안에 w(학습되는 저장소)가 있음.    w: 가중치(파라미터)

In [28]:
# 데이터 세트를 디바이스에 할당.
x, y = x_tensor.to(device), y_tensor.to(device)

In [ ]:
# 디바이스 확인
print(next(model.parameters()).device)
print(x.device, y.device)
# 장치번호 출력

cuda:0
cuda:0 cuda:0


In [30]:
# GPU -> CPU
x_cpu = x.cpu()
# y_cpu = y.cpu()
y_cpu = y.to('cpu') # gpu -> cpu
print(x_cpu.device, y_cpu.device)

cpu cpu


In [32]:
# cpu -> gpu
# x_gpu = x_cpu.to('cuda')
x_gpu = x_cpu.cuda()
print(x_gpu.device)

# 함수로 전체 관리하기 편하니 to(device)로 쓰자. device 바꾸면 다 바뀜.

cuda:0
